version: "3.4"
services:
  setup:
    build: docker/setup
    volumes:
      - .:/app

    #########################################
    #########################################
    ################ 修改这里 ################
    #########################################
    #########################################

    environment:
      #
      # QQ 账号
      QQ: 123456789

      # QQ 密码
      QQ_PASS: qq_password

      # 伪装登录设备
      # ANDROID_PHONE / ANDROID_PAD / ANDROID_WATCH / MACOS / IPAD
      DEVICE: ANDROID_PAD

      # OpenAI session token
      SESSION_TOKEN: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..

      # API KEY (如果你不知道这是什么，可以不用管)
      API_KEY: AnyRandomAPIKey

    #########################################
    #########################################
    ################ 到此为止 ################
    #########################################
    #########################################

  mirai:
    build: docker/mirai
    restart: always
    environment:
      LANG: "C.UTF-8"
    volumes:
      - ./mirai:/mirai
    networks:
      - mirai_network

  chatgpt:
    build: docker/chatgpt
    restart: always
    environment:
      LANG: "C.UTF-8"
      XPRA_PASSWORD: "xpra_password"
    volumes:
      - ./chatgpt/config.json:/app/config.json
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
    networks:
      - mirai_network

networks:
  mirai_network:
